config/routes.rb
Rails.application.routes.draw do
  resources :pontuations
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
   root to: "pontuations#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true

  	#attr_accessor :data, :nome, :idUsuario, :pontos


 	def self.conexao_banco()	
 		#array para salvar as pontuações
 		pontuacoes = []

 		#conexao com o banco
	  	conn = ActiveRecord::Base.connection
	  	#apagar = conn.execute "DELETE FROM Pontuations"

	  	#busca no banco
		result_group = conn.execute "SELECT data, nome, idUsuario, SUM(pontos) FROM Pontuations GROUP BY idUsuario"
		result_group.each do |user|
								
			puts "DATA: #{user[0]}"  
			puts "NOME: #{user[1]}"
			puts "IDUSUARIO: #{user[2]}"
			puts "PONTOS: #{user[3]}"
			
			if user[3] >= 3126
				puts "**** Ótimo desempenho #{user[1]}!! ****"
			end

			puts 

			#cria novo objeto
			pontuacao_atualizada = Pontuation.new(:data => user[0], :nome => user[1], :idUsuario => user[2], :pontos => user[3])


			#adiciona o objeto no array
			pontuacoes << pontuacao_atualizada	

		end

	end
  
end

app/models/pontuation.rb
require 'csv'
class Pontuation < ApplicationRecord


	attr_reader :data, :nome, :idUsuario, :pontos
  	
  	@pontuacoes = []


	def self.read_file(adicionado)
	  	
  		
	  	#caso seja adicionado, o arquivo deve ser lido e inserido no banco
	  	unless (adicionado.empty?)
		  	CSV.foreach(adicionado[0], col_sep: ';').with_index do |row,indice|	
		  		#ignora o cabeçalho  		
		  		unless (indice == 0)
		  			Pontuation.create!(data: row[0], nome: row[1], idUsuario: row[2], pontos: row[3])
		  			puts"******************************"
		  		end
		  		
		  	end
		  	#função para conectar ao banco e agrupar e somar os pontos
		  	@pontuacoes = ApplicationRecord.conexao_banco()
		  	#ApplicationRecord.conexao_banco()
	  	end	  	
  	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

    
end

app/controllers/pontuations_controller.rb
class PontuationsController < ApplicationController
  before_action :set_pontuation, only: [:show, :edit, :update, :destroy]

  # GET /pontuations
  # GET /pontuations.json

  def index
    @pontuations = Pontuation.all
    @pontuacoes = ApplicationRecord.conexao_banco()
  end

  # GET /pontuations/1
  # GET /pontuations/1.json
  def show
  end

  # GET /pontuations/new
  def new
    @pontuation = Pontuation.new
  end

  # GET /pontuations/1/edit
  def edit
  end

  # POST /pontuations
  # POST /pontuations.json
  def create
    @pontuation = Pontuation.new(pontuation_params)

    respond_to do |format|
      if @pontuation.save
        format.html { redirect_to @pontuation, notice: 'Pontuation was successfully created.' }
        format.json { render :show, status: :created, location: @pontuation }
      else
        format.html { render :new }
        format.json { render json: @pontuation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pontuations/1
  # PATCH/PUT /pontuations/1.json
  def update
    respond_to do |format|
      if @pontuation.update(pontuation_params)
        format.html { redirect_to @pontuation, notice: 'Pontuation was successfully updated.' }
        format.json { render :show, status: :ok, location: @pontuation }
      else
        format.html { render :edit }
        format.json { render json: @pontuation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pontuations/1
  # DELETE /pontuations/1.json
  def destroy
    @pontuation.destroy
    respond_to do |format|
      format.html { redirect_to pontuations_url, notice: 'Pontuation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pontuation
      @pontuation = Pontuation.find(params[:id])
      #@pontuacao = Pontuation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pontuation_params
      params.require(:pontuation).permit(:data, :nome, :idUsuario, :pontos)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pontuations_helper.rb
module PontuationsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Gamificacao</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pontuations/_form.html.erb
<div class="container">
  <%= form_with(model: pontuation, local: true) do |form| %>
    <% if pontuation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(pontuation.errors.count, "error") %> prohibited this pontuation from being saved:</h2>

        <ul>
        <% pontuation.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <div class="row">
      <div class="form-group">
          <div class="field">
            <%= form.label :data, class:"control-label col-md-1" %>
            <div class="col-md-8">
              <%= form.date_select :data, id: :pontuation_data, class:"form-control" %>
            </div>
          </div>
      </div>
    </div>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <div class="row">
      <div class="form-group">
        <div class="field">
          <%= form.label :nome, class:"control-label col-md-1" %>
          <div class="col-md-8 ">
            <%= form.text_field :nome, id: :pontuation_nome, class:"form-control" %>
          </div>
        </div>
      </div>
    </div>   
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <div class="row">
      <div class="form-group">
        <div class="field">
          <%= form.label :idUsuario, class:"control-label col-md-1" %>
          <div class="col-md-8">
            <%= form.number_field :idUsuario, id: :pontuation_idUsuario, class:"form-control" %>
          </div>
        </div>
      </div>
    </div>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <div class="row">
      <div class="form-group">
        <div class="field">
          <%= form.label :pontos, class:"control-label col-md-1" %>
          <div class="col-md-8 ">
            <%= form.number_field :pontos, id: :pontuation_pontos, class:"form-control" %>
          </div>
        </div>
      </div>
    </div>
    <td>&nbsp;&nbsp;&nbsp;&nbsp;</td>
    <div class="form-group">
      <div class="actions">
        <%= form.submit class:"btn btn-default"%>
      </div>
    </div>
  <% end %>
</div>

app/views/pontuations/edit.html.erb
<div class="container">

	<div class="panel panel-info"> 
	
		<div class="panel-heading">Editing Pontuation</div>

		<div class="panel-body">
			<%= render 'form', pontuation: @pontuation %>

			<%= link_to 'Show', @pontuation , class:"btn btn-info"%> 
			<%= link_to 'Back', pontuations_path, class:"btn btn-info" %>
		</div>
	</div>
	
</div>

app/views/pontuations/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">

  <h1 class="display-1">Pontuations</h1>
  
  <table class="table">
    <thead>
      <tr>
        <th scope="col">Data</th>
        <th scope="col">Nome</th>
        <th scope="col">Idusuario</th>
        <th scope="col">Pontos</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @pontuacoes.each do |pontuation| %>
        <tr scope="row">
          <td><%= pontuation[0] %></td> 
          <td><%= pontuation[1] %></td>
          <td><%= pontuation[2] %></td>
          <td><%= pontuation[3] %></td>
          
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'New Pontuation', new_pontuation_path, class:"btn btn-info" %>
</div>

app/views/pontuations/new.html.erb
<div class="container">
	
	<div class="panel panel-info"> 

		<div class="panel-heading">New Pontuation</div>

		<div class="panel-body">
				<%= render 'form', pontuation: @pontuation %>

				<%= link_to 'Back', pontuations_path, class:"btn btn-info"%>
		</div>
	</div>
	
</div>

app/views/pontuations/show.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
	  <div class="col-md-4 col-md-offset-0">

		<div class="panel panel-info"> 


			<div class="panel-heading">Pontuação individual</div>

				<div class="panel-body">

					<div style="text-align: center">

						<%= image_tag "profile.png", :size => '80x80' %>
					</div>
					<p>
					  <strong>Data:</strong>
					  <%= @pontuation.data %>
					</p>

					<p>
					  <strong>Nome:</strong>
					  <%= @pontuation.nome %>
					</p>

					<p>
					  <strong>Idusuario:</strong>
					  <%= @pontuation.idUsuario %>
					</p>

					<p>
					  <strong>Pontos:</strong>
					  <%= @pontuation.pontos %>
					</p>

					<%= link_to 'Edit', edit_pontuation_path(@pontuation), class:"btn btn-info" %> 
					<%= link_to 'Back', pontuations_path, class:"btn btn-info" %>
				</div>
		</div>
	</div>
</div>